name: Docker CI

on:
  push:
    branches:
      - devops-learning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install    
        
      - name: Install Frontend Dependencies
        working-directory: ./frontend/realtime-chatapp-frontend
        run: npm install

      - name: Build Angular App
        working-directory: ./frontend/realtime-chatapp-frontend
        run: npm run build

      - name: Build Docker Images
        run: docker compose build